name: hexlet-check

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "change version"
        uses: reedyuk/npm-version@6.0.0
        with:
          version: "6.0.0"
          package: "subproject-directory/"
          git-tag-version: "true"
      - run: make setup
      - run: make start
      - run: make test
      - run: make lint
